In [4]:
import numpy as np

In [7]:
arr = np.ones(5)

In [8]:
arr

array([1., 1., 1., 1., 1.])

In [9]:
arr

array([1., 1., 1., 1., 1.])

In [10]:
arr = np.zeros(6)

In [11]:
arr

array([0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.arange(2,100,2)

In [13]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [15]:
arr2 = np.ones(5)

In [16]:
arr3 = 10*arr2

In [17]:
arr3

array([10., 10., 10., 10., 10.])

In [18]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
np.arange(1,17).reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand()

0.06651469234857132

In [22]:
np.random.rand()

0.8395665623734232

In [23]:
np.random.rand()


0.6023129933986637

In [25]:
np.random.randint(1)

0

In [26]:
np.random.randint(4)

1

In [27]:
np.random.randint(5)

3

In [28]:
np.random.randint(5)

0

In [29]:
np.random.rand(25)

array([0.19826153, 0.38848772, 0.14027474, 0.32942505, 0.12335266,
       0.8137876 , 0.22740724, 0.15803228, 0.46215417, 0.7307533 ,
       0.83847377, 0.70339478, 0.08681498, 0.49409421, 0.81635729,
       0.01388393, 0.87658276, 0.47528132, 0.12316192, 0.75493274,
       0.76465777, 0.01904707, 0.53732947, 0.35970159, 0.53490812])

In [30]:
np.random.rand(24)

array([0.45935791, 0.65607072, 0.36510231, 0.13180844, 0.13879444,
       0.43407779, 0.53360675, 0.52865558, 0.69152652, 0.22120776,
       0.51520117, 0.64137127, 0.80516062, 0.09502844, 0.49065335,
       0.73929754, 0.08234979, 0.37991667, 0.83558019, 0.85569244,
       0.98832731, 0.28843453, 0.10126218, 0.98880601])

In [31]:
np.random.randn(25).reshape(5,5)

array([[-0.39136264, -2.37218433,  1.94813064, -1.09374513,  1.51850231],
       [-2.04459748, -2.21827956,  1.53067791,  0.24224304, -2.560766  ],
       [-0.58380103, -2.36132901,  0.16912288, -0.9587484 ,  0.99016607],
       [ 0.75250048, -0.08227813,  1.7033646 , -0.08439981,  0.88423713],
       [ 0.21752643, -1.77823332, -1.00101271,  1.46534708,  1.41207294]])

In [32]:
np.random.rand(25).reshape(5,5)

array([[0.81749431, 0.15277301, 0.00441877, 0.32389152, 0.79812072],
       [0.25259633, 0.25079643, 0.48736226, 0.88062633, 0.58062093],
       [0.67324549, 0.17686204, 0.27851634, 0.48725641, 0.40008439],
       [0.34471927, 0.49075047, 0.65261352, 0.4047271 , 0.50991273],
       [0.65059694, 0.05450985, 0.13258283, 0.17830195, 0.98308607]])

In [33]:
np.random.gamma(25)

29.43195443244181

In [34]:
np.random.gamma(25).reshape(5,5)

AttributeError: 'float' object has no attribute 'reshape'

In [35]:
np.random.seed

<function RandomState.seed>

In [37]:
a=np.random.seed(3)

In [38]:
a

In [39]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [40]:
np.linspace(1,5,20).reshape(4,5)

array([[1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526],
       [2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684],
       [3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842],
       [4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [44]:
arr = np.arange(1,101).reshape(10,10)

In [45]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [56]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
arr2 = arr.copy

In [59]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [65]:
arr[0:5,4:7]

array([[ 5,  6,  7],
       [15, 16, 17],
       [25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [66]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [67]:
arr[:3,1]

array([ 2, 12, 22])

In [68]:
arr2 = arr[:3,1]

In [69]:
arr2

array([ 2, 12, 22])

In [70]:
arr3 = arr[1:4,2:6]

In [71]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
arr3

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [73]:
arr4 = arr3.copy

In [74]:
arr3

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [75]:
arr4

<function ndarray.copy>

In [77]:
print arr4

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(arr4)? (<ipython-input-77-2fa9c05a1e02>, line 1)

In [78]:
print(arr4)

<built-in method copy of numpy.ndarray object at 0x00000223BD3A8210>


In [79]:
arr = np.random.randint(5)

In [80]:
arr

2

In [86]:
arr = np.random.randn(9) * 5

In [87]:
arr

array([-4.29806896, -2.03957255,  6.23789206, -9.14691842, -7.98258834,
        3.4515602 ,  4.64061229,  7.93268156,  2.00652932])

In [88]:
arr.reshape(3,3)

array([[-4.29806896, -2.03957255,  6.23789206],
       [-9.14691842, -7.98258834,  3.4515602 ],
       [ 4.64061229,  7.93268156,  2.00652932]])

In [89]:
arr.astype(int)

array([-4, -2,  6, -9, -7,  3,  4,  7,  2])

In [91]:
arr2 = arr.reshape(3,3).astype(int)

In [92]:
arr2

array([[-4, -2,  6],
       [-9, -7,  3],
       [ 4,  7,  2]])

In [105]:
arr3 = np.random.randn(9)

In [106]:
arr3

array([-0.78697804, -0.59039268,  1.00420471, -0.01514394, -0.41303679,
        0.00543419, -0.46208081, -0.18511682,  0.35392212])

In [107]:
arr3.reshape(3,3)

array([[-0.78697804, -0.59039268,  1.00420471],
       [-0.01514394, -0.41303679,  0.00543419],
       [-0.46208081, -0.18511682,  0.35392212]])

In [108]:
arr2 * arr3

ValueError: operands could not be broadcast together with shapes (3,3) (9,) 

In [109]:
np.matmul(arr2,arr3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 9 is different from 3)

In [110]:
arr = [[2,3],[4,5]]

In [111]:
arr

[[2, 3], [4, 5]]

In [112]:
arr.reshape(2,2)

AttributeError: 'list' object has no attribute 'reshape'

In [123]:
arr = np.random.rand(4) *5


In [124]:
ar

NameError: name 'ar' is not defined

In [125]:
arr.astype(int)

array([4, 2, 4, 1])

In [127]:
arr2 =np.random.rand(4)*5

In [128]:
arr2

array([1.01438827, 4.79168117, 3.8307638 , 0.94125426])

In [135]:
arr_new2 =arr2.astype(int).reshape(2,2)

In [137]:
arr_new = arr.astype(int).reshape(2,2)

In [131]:
arr2

array([1.01438827, 4.79168117, 3.8307638 , 0.94125426])

In [132]:
arr2.reshape(2,2)

array([[1.01438827, 4.79168117],
       [3.8307638 , 0.94125426]])

In [138]:
np.matmul(arr_new,arr_new2)

array([[10, 16],
       [ 7, 16]])

In [139]:
arr_new

array([[4, 2],
       [4, 1]])

In [140]:
arr_new2

array([[1, 4],
       [3, 0]])

In [142]:
arr_new.mean()

2.75

In [148]:
arr_new.sum()

11

In [149]:
arr_new

array([[4, 2],
       [4, 1]])

In [150]:
np.linalg.det(arr_new)

-4.0

In [151]:
np.linalg.det(arr_new2)

-12.0

In [152]:
arr_new3 = np.random.rand(6) *5


In [153]:
arr_new3

array([0.07464103, 2.05342852, 3.64023685, 1.81776214, 0.37112054,
       4.78322752])

In [154]:
arr_new3 = arr_new3.reshape(2,3)

In [155]:
arr_new3

array([[0.07464103, 2.05342852, 3.64023685],
       [1.81776214, 0.37112054, 4.78322752]])

In [156]:
np.linalg.det(arr_new3)

LinAlgError: Last 2 dimensions of the array must be square